#!/usr/bin/env python3
"""Generate a Mermaid architecture diagram from a local repo path or public GitHub URL."""

from __future__ import annotations

import argparse
import ast
import os
import re
import subprocess
import tempfile
from pathlib import Path
from typing import Iterable

EXCLUDED_DIRS = {
    ".git",
    ".github",
    "node_modules",
    "dist",
    "build",
    ".venv",
    "venv",
    "__pycache__",
}

MAX_LABEL = 42


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate a Mermaid architecture diagram from repository contents."
    )
    source = parser.add_mutually_exclusive_group(required=True)
    source.add_argument("--repo-url", help="Public GitHub repository URL")
    source.add_argument("--repo-path", help="Path to a local repository", default=None)
    parser.add_argument(
        "--output",
        required=True,
        help="Output Mermaid file path (e.g. docs/architecture.mmd)",
    )
    parser.add_argument(
        "--max-files",
        type=int,
        default=800,
        help="Maximum files to include in the architecture view.",
    )
    return parser.parse_args()


def clone_public_repo(url: str) -> Path:
    match = re.match(r"https://github\.com/([\w.-]+)/([\w.-]+?)(?:\.git)?/?$", url)
    if not match:
        raise ValueError(
            "Only public GitHub URLs are supported. Example: https://github.com/org/repo"
        )

    tmp_root = Path(tempfile.mkdtemp(prefix="merman-"))
    repo_dir = tmp_root / "repo"
    subprocess.run(
        ["git", "clone", "--depth", "1", url, str(repo_dir)],
        check=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
    )
    return repo_dir


def sanitize_node_id(value: str) -> str:
    return re.sub(r"[^a-zA-Z0-9_]", "_", value)


def shorten_label(label: str) -> str:
    if len(label) <= MAX_LABEL:
        return label
    return f"...{label[-(MAX_LABEL - 3):]}"


def should_exclude(path: Path) -> bool:
    return any(part in EXCLUDED_DIRS for part in path.parts)


def list_repo_files(repo_path: Path, max_files: int) -> list[Path]:
    files: list[Path] = []
    for candidate in sorted(repo_path.rglob("*")):
        if should_exclude(candidate.relative_to(repo_path)):
            continue
        if candidate.is_file():
            files.append(candidate)
            if len(files) >= max_files:
                break
    return files


def top_level_components(repo_path: Path, files: Iterable[Path]) -> set[str]:
    components: set[str] = set()
    for file_path in files:
        rel = file_path.relative_to(repo_path)
        components.add(rel.parts[0])
    return components


def parse_python_imports(repo_path: Path, files: Iterable[Path]) -> list[tuple[str, str]]:
    edges: list[tuple[str, str]] = []
    package_roots = top_level_components(repo_path, files)

    for file_path in files:
        if file_path.suffix != ".py":
            continue

        rel = file_path.relative_to(repo_path)
        src = rel.parts[0]

        try:
            tree = ast.parse(file_path.read_text(encoding="utf-8"))
        except (SyntaxError, UnicodeDecodeError):
            continue

        for node in ast.walk(tree):
            mod_name = None
            if isinstance(node, ast.Import):
                for alias in node.names:
                    mod_name = alias.name.split(".")[0]
                    if mod_name in package_roots and mod_name != src:
                        edges.append((src, mod_name))
            elif isinstance(node, ast.ImportFrom) and node.module:
                mod_name = node.module.split(".")[0]
                if mod_name in package_roots and mod_name != src:
                    edges.append((src, mod_name))

    return sorted(set(edges))


def make_diagram(repo_path: Path, files: list[Path]) -> str:
    repo_name = repo_path.name
    components = sorted(top_level_components(repo_path, files))
    import_edges = parse_python_imports(repo_path, files)

    lines: list[str] = []
    lines.append("%% Generated by merman. DO NOT EDIT BY HAND.")
    lines.append("flowchart TD")
    lines.append(f'    root["{shorten_label(repo_name)}"]')

    for component in components:
        node_id = sanitize_node_id(f"component_{component}")
        lines.append(f'    {node_id}["{shorten_label(component)}"]')
        lines.append(f"    root --> {node_id}")

    if import_edges:
        lines.append("")
        lines.append("    %% Python import dependencies inferred from source")
        for src, target in import_edges:
            src_id = sanitize_node_id(f"component_{src}")
            target_id = sanitize_node_id(f"component_{target}")
            lines.append(f"    {src_id} -.imports.-> {target_id}")

    lines.append("")
    lines.append("    %% Sample of files per component")
    component_samples: dict[str, list[str]] = {name: [] for name in components}
    for file_path in files:
        rel = file_path.relative_to(repo_path)
        component = rel.parts[0]
        if len(component_samples[component]) < 4:
            component_samples[component].append(str(rel))

    for component, sample_files in sorted(component_samples.items()):
        comp_id = sanitize_node_id(f"component_{component}")
        for file_name in sample_files:
            file_id = sanitize_node_id(f"file_{file_name}")
            lines.append(f'    {file_id}["{shorten_label(file_name)}"]')
            lines.append(f"    {comp_id} --> {file_id}")

    return "\n".join(lines) + "\n"


def main() -> int:
    args = parse_args()

    if args.repo_url:
        repo_path = clone_public_repo(args.repo_url)
    else:
        repo_path = Path(args.repo_path).resolve()

    if not repo_path.exists():
        raise FileNotFoundError(f"Repository path does not exist: {repo_path}")

    files = list_repo_files(repo_path, args.max_files)
    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    diagram = make_diagram(repo_path, files)
    output_path.write_text(diagram, encoding="utf-8")

    print(f"Generated {output_path} from {repo_path} ({len(files)} files scanned).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
